-- =============================================================
-- schema.sql — StreamPilot database schema
--
-- Run once with: python init_db.py
-- For live schema changes use the migrations/ folder.
--
-- Design rules:
--   Auto-increment integer primary keys throughout
--   All channels share one database, isolated by channel_id
--   Soft delete (deleted_at) where data should be recoverable
--   Hard delete where rows are truly disposable
--   Platform-agnostic — built for Twitch now, YouTube and
--   TikTok later without schema changes
-- =============================================================

PRAGMA foreign_keys = ON;


-- =============================================================
-- STREAMER SIDE
-- =============================================================

-- -------------------------------------------------------------
-- Users
-- One row per StreamPilot account.
-- No platform-specific columns here — platform identity lives
-- in user_platforms so one account can connect multiple platforms.
-- Created automatically on first login via any platform OAuth.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    email         TEXT    UNIQUE,
    display_name  TEXT    NOT NULL,
    avatar_url    TEXT,
    tier          TEXT    NOT NULL DEFAULT 'free',
    created_at    TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TEXT
);


-- -------------------------------------------------------------
-- User platforms
-- One row per platform connection per user.
-- A user can connect Twitch today and YouTube later —
-- both rows link back to the same user_id.
-- platform: twitch | youtube | tiktok
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_platforms (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id               INTEGER NOT NULL REFERENCES users(id),
    platform              TEXT    NOT NULL,
    platform_user_id      TEXT    NOT NULL,
    platform_login        TEXT    NOT NULL,
    platform_display_name TEXT    NOT NULL,
    platform_avatar_url   TEXT,
    access_token          TEXT,
    refresh_token         TEXT,
    created_at            TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at         TEXT,
    UNIQUE(platform, platform_user_id)
);


-- -------------------------------------------------------------
-- Channels
-- Every streamer gets a channel record per platform they connect.
-- platform tells the backend which API to call for stream data.
-- platform_channel_id is the platform's own ID for the channel.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS channels (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id             INTEGER NOT NULL REFERENCES users(id),
    platform            TEXT    NOT NULL DEFAULT 'twitch',
    platform_channel_id TEXT    NOT NULL,
    created_at          TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(platform, platform_channel_id)
);


-- -------------------------------------------------------------
-- Team members
-- Mods and lead mods invited to a channel.
-- They sign in with their own platform account.
-- accepted_at is NULL until they click the invite link.
-- role: mod | lead_mod
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team_members (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id  INTEGER NOT NULL REFERENCES channels(id),
    user_id     INTEGER NOT NULL REFERENCES users(id),
    role        TEXT    NOT NULL DEFAULT 'mod',
    invited_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accepted_at TEXT,
    UNIQUE(channel_id, user_id)
);


-- -------------------------------------------------------------
-- Invite tokens
-- Generated when a streamer invites a mod.
-- Included in the invite link sent to the mod.
-- Single use — marked used_at once accepted.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invite_tokens (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id  INTEGER NOT NULL REFERENCES channels(id),
    token       TEXT    NOT NULL UNIQUE,
    role        TEXT    NOT NULL DEFAULT 'mod',
    email       TEXT,
    created_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at  TEXT    NOT NULL,
    used_at     TEXT
);


-- -------------------------------------------------------------
-- Beta codes
-- Generated by admin. One code per invited beta user.
-- Redeemed at /beta/<code> before platform login.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS beta_codes (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    code        TEXT    NOT NULL UNIQUE,
    note        TEXT,
    created_by  INTEGER NOT NULL,
    created_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at  TEXT,
    used_at     TEXT,
    used_by     INTEGER REFERENCES users(id)
);


-- -------------------------------------------------------------
-- Overlay tokens
-- One token per overlay type per channel.
-- Lives in the OBS browser source URL.
-- Regenerating instantly invalidates the old URL.
-- overlay_type: alerts | panels | celebrations
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS overlay_tokens (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id   INTEGER NOT NULL REFERENCES channels(id),
    overlay_type TEXT    NOT NULL,
    token        TEXT    NOT NULL UNIQUE,
    created_at   TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(channel_id, overlay_type)
);


-- -------------------------------------------------------------
-- Commands
-- Chat commands the bot responds to e.g. !discord !socials
-- Soft deleted so history is preserved.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS commands (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id  INTEGER NOT NULL REFERENCES channels(id),
    trigger     TEXT    NOT NULL,
    response    TEXT    NOT NULL,
    enabled     INTEGER NOT NULL DEFAULT 1,
    cooldown_s  INTEGER NOT NULL DEFAULT 30,
    created_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TEXT,
    UNIQUE(channel_id, trigger)
);


-- -------------------------------------------------------------
-- Alert configs
-- One row per alert type per channel.
-- Created with defaults when a channel is first set up.
-- alert_type: follow | sub_t1 | sub_t2 | sub_t3 |
--             gift_sub | raid | bits | resub
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alert_configs (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id    INTEGER NOT NULL REFERENCES channels(id),
    alert_type    TEXT    NOT NULL,
    enabled       INTEGER NOT NULL DEFAULT 1,
    message_text  TEXT,
    duration_ms   INTEGER NOT NULL DEFAULT 5000,
    sound_enabled INTEGER NOT NULL DEFAULT 1,
    UNIQUE(channel_id, alert_type)
);


-- -------------------------------------------------------------
-- Timed panels
-- Panels that appear on stream on a schedule.
-- Soft deleted so streamers can recover accidental deletes.
-- schedule_mode: interval | fixed_time
-- content_type:  static | animated_file | css
-- anim_speed:    slow | normal | fast
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS panels (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id      INTEGER NOT NULL REFERENCES channels(id),
    name            TEXT    NOT NULL,
    content_type    TEXT    NOT NULL DEFAULT 'static',
    content_data    TEXT,
    schedule_mode   TEXT    NOT NULL DEFAULT 'interval',
    interval_mins   INTEGER,
    fixed_minute    INTEGER,
    duration_ms     INTEGER NOT NULL DEFAULT 8000,
    entry_animation TEXT    NOT NULL DEFAULT 'fade',
    exit_animation  TEXT    NOT NULL DEFAULT 'fade',
    anim_speed      TEXT    NOT NULL DEFAULT 'normal',
    enabled         INTEGER NOT NULL DEFAULT 1,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TEXT
);


-- -------------------------------------------------------------
-- Event log
-- Every notable stream event logged here.
-- Used for the dashboard event feed and future analytics.
-- Hard deleted by age — old logs pruned on a schedule.
-- event_type: follow | sub | raid | bits | command_used etc.
-- event_data: JSON blob with extra detail per event type
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id  INTEGER NOT NULL REFERENCES channels(id),
    event_type  TEXT    NOT NULL,
    event_data  TEXT,
    occurred_at TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- -------------------------------------------------------------
-- Viewer stats cache
-- Twitch viewer count only updates every ~2 minutes.
-- We store the last known value so the UI can show
-- "last updated 14:32" rather than pretending it is live.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS viewer_stats (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    channel_id    INTEGER NOT NULL REFERENCES channels(id),
    viewer_count  INTEGER NOT NULL DEFAULT 0,
    recorded_at   TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =============================================================
-- ADMIN SIDE
-- Completely separate from streamer tables.
-- No platform integration. Username and password only.
-- =============================================================

-- -------------------------------------------------------------
-- Admin users
-- Created by the owner only. Never self-registered.
-- role: owner | manager | worker
-- must_change_password: set to 1 to force reset on next login
-- active: set to 0 to disable without deleting
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    username             TEXT    NOT NULL UNIQUE,
    email                TEXT    NOT NULL UNIQUE,
    password_hash        TEXT    NOT NULL,
    role                 TEXT    NOT NULL DEFAULT 'worker',
    password_changed_at  TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    password_expires_at  TEXT    NOT NULL DEFAULT (datetime('now', '+45 days')),
    must_change_password INTEGER NOT NULL DEFAULT 0,
    last_login_at        TEXT,
    created_by           INTEGER REFERENCES admin_users(id),
    created_at           TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active               INTEGER NOT NULL DEFAULT 1
);


-- -------------------------------------------------------------
-- Admin password history
-- Last 6 password hashes stored per admin user.
-- New password checked against all 6 before saving.
-- Oldest entry pruned when history exceeds 6.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_password_history (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    admin_user_id  INTEGER NOT NULL REFERENCES admin_users(id),
    password_hash  TEXT    NOT NULL,
    created_at     TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------
-- Beta access requests
-- Submitted via the public /beta page.
-- Reviewed in the admin panel — admin generates a code when approved.
-- status: pending | approved | rejected
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS beta_requests (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    name         TEXT    NOT NULL,
    email        TEXT    NOT NULL UNIQUE,
    twitch_login TEXT,
    reason       TEXT,
    status       TEXT    NOT NULL DEFAULT 'pending',
    created_at   TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at  TEXT,
    reviewed_by  INTEGER REFERENCES admin_users(id)
);